# Generated by Django 4.1.7 on 2023-04-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BranchIngredients',
            new_name='BranchIngredient',
        ),
        migrations.RenameField(
            model_name='branchingredient',
            old_name='ingredient',
            new_name='ingredient_id',
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['restaurant_id'], name='restaurant__restaur_b99d64_idx'),
        ),
        migrations.AddIndex(
            model_name='branchingredient',
            index=models.Index(fields=['ingredient_id'], name='restaurant__ingredi_a8839b_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['branch_id'], name='restaurant__branch__c29790_idx'),
        ),
        migrations.AddIndex(
            model_name='menuposition',
            index=models.Index(fields=['menu_id'], name='restaurant__menu_id_bb20bc_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['branch_id'], name='restaurant__branch__a21e49_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order_id'], name='restaurant__order_i_7a61a8_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['branch_id'], name='restaurant__branch__de0911_idx'),
        ),
        migrations.AddIndex(
            model_name='waiter',
            index=models.Index(fields=['branch_id'], name='restaurant__branch__2c071a_idx'),
        ),
    ]
