# Generated by Django 4.1.7 on 2023-05-11 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_branch_restaurant__restaur_b99d64_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='waiter',
            options={'ordering': ['surname']},
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='branchingredient',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='branch_id',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='menuposition',
            old_name='menu_id',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='branch_id',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='table_id',
            new_name='table',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='waiter_id',
            new_name='waiter',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='menu_position_id',
            new_name='menu_position',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='reserved_id',
            new_name='reserved',
        ),
        migrations.RenameField(
            model_name='waiter',
            old_name='branch_id',
            new_name='branch',
        ),
    ]
