# Generated by Django 4.1.7 on 2023-05-11 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_restaurant_options_alter_waiter_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='branch_id',
            new_name='branch',
        ),
    ]
