# Generated by Django 4.1.7 on 2023-06-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_rename_branch_id_table_branch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='MenuCategory',
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['restaurant']},
        ),
        migrations.RenameField(
            model_name='menuposition',
            old_name='menu',
            new_name='menu_category',
        ),
        migrations.AddField(
            model_name='menuposition',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuposition',
            name='weight_unit',
            field=models.CharField(default='gramm', max_length=10),
            preserve_default=False,
        ),
    ]
