# Generated by Django 4.1.7 on 2023-06-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_rename_menu_menucategory_alter_branch_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'verbose_name_plural': 'Menu categories'},
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='logo_path',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(default='images/logos/no-logo-image.jpg', upload_to='images/logos/'),
        ),
    ]
